### ISSUE TITLE
Duplicated BitBar

### ISSUE THREAD

**Issue by oscard0m** [stefanosaittamrf/assigned-pr-counter-marfeel#10]
I don't know if this happens to me or to everybody: When I run BitBar, two instances of it appear on my Status Bar. The right one and another one with a Warning ⚠️  icon.

![image](https://cloud.githubusercontent.com/assets/2574275/17105621/4dfbda32-5288-11e6-9ba3-7cb0c8c38796.png)

**Comment by stefanosaittamrf** [comment]
What's inside of the warning? I guess you have 2 plugin into the directory

**Comment by oscard0m** [comment]
It seems that there were more than one files in the plugin object (the .git, README.md, etc and it tried to load them).
