### ISSUE TITLE
Display Proper Error UI when the API limit Request has reached its limit

### ISSUE THREAD

**Issue by oscard0m** [stefanosaittamrf/assigned-pr-counter-marfeel#22]
![image](https://cloud.githubusercontent.com/assets/2574275/21297300/6154ce1e-c57d-11e6-8696-ca82f091589e.png)

_Ref:_ https://developer.github.com/v3/#rate-limiting

**Comment by stefanosaittamrf** [comment]
I would like to reference: #25 

This issue can be solve consequentially providing a cool Error Handling architecture.

**Comment by oscard0m** [comment]
Close due to inactivity
