### ISSUE TITLE
Check for multi-assignee Pull Request

### ISSUE THREAD

**Issue by stefanosaittamrf** [stefanosaittamrf/assigned-pr-counter-marfeel#7]
### Description

Will be useful to check even for multi-assignee pull request in order to don't loose something that will should track instead.

**Comment by oscard0m** [comment]
It's done

**Comment by stefanosaittamrf** [comment]
❓

**Comment by oscard0m** [comment]
The plugin is already checking for multi-assigned PR right?

**Comment by stefanosaittamrf** [comment]
Actually no, because i guess than when there are multiple assignee to a PR, the github API will return an array-like structure into the response JSON, so i have to introduce this functionality
