### ISSUE TITLE
To count the total number of open pull requests assigned

### ISSUE THREAD

**Issue by oscard0m** [stefanosaittamrf/assigned-pr-counter-marfeel#8]
![image](https://cloud.githubusercontent.com/assets/2574275/17105554/0c9c0800-5288-11e6-8876-fa4e7643a1e2.png)

**Comment by stefanosaittamrf** [comment]
This will be very cool to have it. Feel free to pull request this!

**Comment by oscard0m** [comment]
I have my PR ready. Give me access to do a push to your repo please 😄 
![image](https://cloud.githubusercontent.com/assets/2574275/17120767/da39b988-52ce-11e6-9695-8191bd78e2e2.png)

**Comment by stefanosaittamrf** [comment]
![powa](http://i.giphy.com/XwOdlIdTnN0vS.gif)

Now its possible to open PR for anybody 🎉
