### ISSUE TITLE
Sometimes appear the text 'MarfeelXP' instead of the glasses with the number of pull-requests

### ISSUE THREAD

**Issue by oscard0m** [stefanosaittamrf/assigned-pr-counter-marfeel#9]
![image](https://cloud.githubusercontent.com/assets/2574275/17105594/32d82e72-5288-11e6-86f7-0bcbc2e2590f.png)

**Comment by stefanosaittamrf** [comment]
This is a known bug, i'm about to release a fix ASAP. 🚕
